import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../globals.css'
import {cn} from '@/lib/utils'
import Header from '@/components/header/Header'
import Footer from '@/components/Footer'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Header />
      <div className="mx-auto max-w-[1200px] mt-[100px] mb-[48px] w-full">
        {children}
      </div>
      <Footer />
    </>
  )
}
